name: notify

on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_notification: true
          disable_web_page_preview: true
          format: markdown
          message: |
            ${{ github.actor }} created commit in [${{ github.repository }}](https://github.com/${{ github.repository }}):

            ${{ github.event.commits[0].message }}

            [commit link](https://github.com/${{ github.repository }}/commit/${{github.sha}})
